### ISSUE TITLE
Extend to other domains?

### ISSUE THREAD

**Issue by yoeldk** [oneil512/INSIGHT#20]
Is there a possibility to extend this tool to other domains than medical research?
Say I have a bunch of documents and a list of tasks to perform on them (search for specific data points, extract insights based on connected data points from different documents, etc). 
TIA!

**Comment by oneil512** [comment]
This is definitely possible, but a big problem with current agent is that they try to do too many things. Here we are focusing on the medical research vertical, which allows us to actually get useful outputs.

The general architecture can be applied to anything, and the parameters are the tools and prompts that you input.
