### ISSUE TITLE
Use Turbo as default?

### ISSUE THREAD

**Issue by oaustegard** [oneil512/INSIGHT#34]
Just based on the 10x price difference would it make sense to use gpt-3.5-turbo as the default model, even for individual completion calls?

A basic shim like this (generated by GPT-4) could plausibly be added to utils.py to allow this even for calls to `get_gpt_completion`: https://austegard.com/pv?d56d5a68a610a29ee7e353616a480628 (Scroll down to white code block)

Also would suggest moving the hardcoded engine strings to config.py

PS! Loved the demo during the 🦙-index meetup!

**Comment by oneil512** [comment]
This is great! please open a PR :)

I did try using gpt-3.5-turbo at one point and noticed a lot of variance and chatty-ness, but I just tested it briefly so maybe I didn't give it enough of a chance, or maybe some prompt tweaks could make it better

**Comment by oneil512** [comment]
Retested this and turbo works well now. Switched.
